export const boardMembers = [
  {
    slug: 'haja-mariama-turay',
    name: 'Miss. Haja Mariama Turay',
    position: 'Chairperson',
    portfolio: 'Health-System Strengthening & Strategic Partnerships',
    programme: 'health-systems',
    location: 'Makeni City, Sierra Leone',
    phone: '+23278968528',
    email: 'mariamahajaturaymchf@gmail.com',
    image: '/images/board/haja-mariama-turay.jpg',
    photoPosition: '50% 38%',
  },
  {
    slug: 'abdul-kamara',
    name: 'Mr. Abdul Kamara',
    position: 'Executive Director',
    boardRole: 'Vice-chairperson',
    portfolio: 'Reproductive, Maternal, Newborn & Child Health',
    programme: 'rmnch',
    location: 'Freetown, Sierra Leone',
    phone: '+23278609458',
    email: 'kamaramchf@gmail.com',
    image: '/images/board/abdul-kamara.jpg',
    photoPosition: '50% 35%',
  },
  {
    slug: 'bintou-kaba',
    name: 'Dr. Bintou Kaba',
    position: 'Executive Director',
    portfolio: 'Immunization, Vaccine Confidence, Disease Control & Prevention',
    programme: 'immunization',
    location: 'Conakry, Guinea',
    phone: '+224628654387',
    email: 'bintoumchf@gmail.com',
    image: '/images/board/bintou-kaba.jpg',
    photoPosition: '45% 35%',
  },
  {
    slug: 'yalanie-alhassan-turay',
    name: 'Mr. Yalanie Alhassan Turay',
    position: 'Executive Director',
    portfolio: 'Community Health, Empowerment & Health Equity',
    programme: 'community-health',
    location: 'Freetown, Sierra Leone',
    phone: '+23274200493',
    email: 'yalaniealhassanmch@gmail.com',
    image: '/images/board/yalanie-alhassan-turay.jpg',
    photoPosition: '50% 30%',
  },
  {
    slug: 'haja-mariama-tury',
    name: 'Haja Mariama Tury',
    position: 'Executive Director',
    boardRole: 'Treasurer',
    portfolio: 'Research, Evidence, Innovation & MEL',
    programme: 'research-innovation',
    location: 'Makeni City, Sierra Leone',
    phone: '+23276271553',
    email: 'johnnetsesaymchf@gmail.com',
    image: '/images/board/haja-mariama-tury.jpg',
    photoPosition: '50% 35%',
  },
];
