export const boardMembers = [
  {
    id: 'board-haja-mariama-turay',
    slug: 'mariama-haja-turay',
    legacySlug: 'haja-mariama-turay',
    previousName: 'Miss. Haja Mariama Turay',
    name: 'Miss. Mariama Haja Turay',
    position: 'Chairperson',
    portfolio: 'Health-System Strengthening & Strategic Partnerships',
    portfolioSummary: 'Building resilient health systems through strategic partnerships, local capacity strengthening, and data-driven solutions that improve maternal, newborn, child, and community health outcomes.',
    programme: 'health-systems',
    location: 'Makeni City, Sierra Leone',
    phone: '+23278968528',
    email: 'mariamahajaturaymchf@gmail.com',
    image: '/images/board/haja-mariama-turay.jpg',
    photoPosition: '50% 38%',
  },
  {
    id: 'board-abdul-kamara',
    slug: 'abdul-kamara',
    name: 'Mr. Abdul Kamara',
    position: 'Executive Director',
    boardRole: 'Vice-chairperson',
    portfolio: 'Reproductive, Maternal, Newborn & Child Health',
    portfolioSummary: 'Ensuring every woman, newborn, and child has access to quality, equitable healthcare through integrated services, community engagement, and resilient health systems.',
    programme: 'rmnch',
    location: 'Freetown, Sierra Leone',
    phone: '+23278609458',
    email: 'kamaramchf@gmail.com',
    image: '/images/board/abdul-kamara.jpg',
    photoPosition: '50% 35%',
  },
  {
    id: 'board-bintou-kaba',
    slug: 'bintou-kaba',
    name: 'Dr. Bintou Kaba',
    position: 'Executive Director',
    portfolio: 'Immunization, Vaccine Confidence, Disease Control & Prevention',
    portfolioSummary: 'Strengthening immunization systems, building vaccine confidence, and advancing disease prevention through community engagement, evidence-based interventions, surveillance, and equitable access to life-saving vaccines and health services.',
    programme: 'immunization',
    location: 'Conakry, Guinea',
    phone: '+224628654387',
    email: 'bintoumchf@gmail.com',
    image: '/images/board/bintou-kaba.jpg',
    photoPosition: '45% 35%',
  },
  {
    id: 'board-yalanie-alhassan-turay',
    slug: 'yalanie-alhassan-turay',
    name: 'Mr. Yalanie Alhassan Turay',
    position: 'Executive Director',
    portfolio: 'Community Health, Empowerment & Health Equity',
    portfolioSummary: 'Strengthening community systems, promoting inclusive participation, and advancing health equity to improve well-being, resilience, and opportunities for vulnerable populations.',
    programme: 'community-health',
    location: 'Freetown, Sierra Leone',
    phone: '+23274200493',
    email: 'yalaniealhassanmch@gmail.com',
    image: '/images/board/yalanie-alhassan-turay.jpg',
    photoPosition: '50% 30%',
  },
  {
    id: 'board-haja-mariama-tury',
    slug: 'johnnet-sesay',
    legacySlug: 'haja-mariama-tury',
    previousName: 'Haja Mariama Tury',
    name: 'Johnnet Sesay',
    position: 'Executive Director',
    boardRole: 'Treasurer',
    portfolio: 'Research, Evidence, Innovation & MEL',
    portfolioSummary: 'Transforming data into action through research, innovation, and robust MEL systems that demonstrate impact, strengthen accountability, and guide evidence-based investments.',
    programme: 'research-innovation',
    location: 'Makeni City, Sierra Leone',
    phone: '+23276271553',
    email: 'johnnetsesaymchf@gmail.com',
    image: '/images/board/haja-mariama-tury.jpg',
    photoPosition: '50% 35%',
  },
];
