import {boardMembers} from './board';
import {pageCatalog} from './page-catalog';
import {programmeLessons,learningGuideBody} from './education';
import source from './programmes.json';
export type ContentRecord={id:string;kind:string;slug:string;title:string;summary:string;body:string;status:string;programme:string;year:string;topic:string;location:string;image:string;file:string;source:string;meta:Record<string,any>;updatedAt?:string};
const slugs=['rmnch','immunization','community-health','research-innovation','health-systems'];
export const programmes=source.map((p,i)=>({...p,id:'programme-'+slugs[i],slug:slugs[i],number:String(i+1).padStart(2,'0'),image:['/images/hero.jpg','/images/immunization.jpg','/images/mother-child.jpg','/images/health-worker.jpg','/images/health-worker.jpg'][i],shortTitle:['Maternal & child health','Immunization & prevention','Community health & equity','Research & innovation','Health systems & partnerships'][i]}));
export const values=[['Equity','A fair opportunity for better health, with particular attention to underserved and vulnerable communities.'],['Evidence & Excellence','Scientific evidence, reliable data and professional standards guide our work and continuous improvement.'],['Integrity & Accountability','Honesty, transparency and responsible stewardship of resources, accountable to communities and partners.'],['Innovation & Empowerment','Practical solutions that equip people with knowledge, skills and confidence to improve their health.'],['People & Impact','People’s dignity, needs and well-being are at the centre of meaningful and sustainable change.']];
export const priorities=['Gender & social inclusion','Youth participation','Community ownership','Evidence-based programming','Partnership & coordination','Monitoring, Evaluation & Learning','Sustainability'];
export const mission='To advance equitable and sustainable health outcomes for adolescents, young people, women, newborns and children through integrated, evidence-based solutions that strengthen reproductive and maternal health, child health, immunization, disease control and prevention, community action, research and innovation.';
export const kinds=['page','programme','intervention','activity','project','research','publication','report','news','insight','event','leadership','partner','impact','story','resource','career','contact','setting'];
const make=(x:Partial<ContentRecord>&Pick<ContentRecord,'id'|'kind'|'slug'|'title'|'summary'>):ContentRecord=>({body:'',status:'published',programme:'',year:'',topic:'',location:'',image:'',file:'',source:'MCHF Strategic Plan 2027–2031',meta:{},...x});
export const baseRecords:ContentRecord[]=[
 ...pageCatalog.filter(p=>p.path!=='about').map(p=>make({id:'page-'+p.path.replaceAll('/','-'),kind:'page',slug:p.path,title:p.title,summary:p.summary,meta:{destination:p.path}})),
 ...boardMembers.map((m,i)=>make({id:'board-'+m.slug,kind:'leadership',slug:m.slug,title:m.name,summary:m.portfolio,body:`${m.name} serves as ${m.position}${m.boardRole?' and '+m.boardRole:''}, with the ${m.portfolio} portfolio.`,programme:m.programme,location:m.location,image:m.image,source:'MCHF Board of Directors',meta:{position:m.position,boardRole:m.boardRole||'',portfolio:m.portfolio,email:m.email,phone:m.phone,order:i,alt:'Portrait of '+m.name,photoPosition:m.photoPosition}})),
 ...Object.entries(programmeLessons).map(([slug,lesson])=>make({id:'guide-'+slug,kind:'resource',slug:'understanding-'+slug,title:lesson.title,summary:lesson.intro,programme:slug,topic:'Public-health concepts',image:lesson.image||'',body:learningGuideBody(slug,lesson),meta:{format:'HTML',documentType:'Learning guide',furtherReadingUrl:lesson.link?.[1],furtherReadingLabel:lesson.link?.[0],alt:'AI-generated educational illustration: '+lesson.title}})),
 ...programmes.map(p=>make({id:p.id,kind:'programme',slug:p.slug,title:p.title,summary:p.subtitle,body:p.interventions.map(x=>x.title).join('\n'),programme:p.slug,year:'2027',image:p.image,meta:{interventions:p.interventions}})),
 ...programmes.flatMap(p=>p.interventions.flatMap((x,i)=>[make({id:`${p.slug}-intervention-${i}`,kind:'intervention',slug:`${p.slug}-${i}`,title:x.title,summary:x.activities.join(' · '),programme:p.slug,meta:{parentId:p.id,activities:x.activities}}),...x.activities.map((a,j)=>make({id:`${p.slug}-activity-${i}-${j}`,kind:'activity',slug:`${p.slug}-${i}-${j}`,title:a,summary:`A strategic priority under ${x.title}.`,programme:p.slug,meta:{parentId:`${p.slug}-intervention-${i}`,timeline:'2027–2031',targetDirection:'Progressive improvement from baseline; annual targets set through work planning.'}}))])),
 make({id:'strategic-plan',kind:'publication',slug:'strategic-plan-2027-2031',title:'MCHF Strategic Plan 2027–2031',summary:'Our integrated five-year framework for equitable health: five programme areas, 26 interventions, implementation, learning and accountability.',year:'2027',topic:'Institutional strategy',file:'/documents/MCHF_Strategic_Plan_2027-2031.pptx',meta:{format:'PPTX',documentType:'Strategic document',author:'Maternal and Child Health Foundation',view:'/strategic-plan-2027-2031'}}),
 make({id:'memorandum',kind:'publication',slug:'memorandum-and-articles',title:'Memorandum & Articles of Association',summary:'The Foundation’s objectives, governance structure, five strategic portfolios and institutional accountability framework.',topic:'Governance',file:'/documents/MCHF_Memorandum_and_Articles_of_Association.docx',source:'MCHF Memorandum & Articles of Association',meta:{format:'DOCX',documentType:'Governance document',author:'Maternal and Child Health Foundation',view:'/about/governance'}}),
 make({id:'resource-community-ownership',kind:'resource',slug:'community-ownership-in-practice',title:'What community ownership means in practice',summary:'Why local priorities, meaningful youth participation and trusted community networks are central to the MCHF approach.',programme:'community-health',topic:'Community ownership',image:'/images/mother-child.jpg',body:'Community ownership is one of the seven cross-cutting principles in MCHF’s Strategic Plan 2027–2031. It asks programmes to involve communities in identifying health priorities and developing practical, local solutions.\nMeaningful participation goes beyond receiving information. The strategy provides for youth and community dialogues, engagement with women’s groups and local leaders, and platforms for adolescents and young people to contribute to programme decision-making.\nCommunity champions and peer educators are another part of this approach. Planned activities include orientation, training and mentorship, peer-support initiatives, accurate health information and links to appropriate services.\nInclusion is essential. The framework calls for identifying social, geographical and economic access barriers and prioritising underserved and vulnerable communities in outreach and programme design.\nThese are strategic commitments. Confirmed projects, community stories and verified results will be published as implementation develops.',meta:{format:'HTML',documentType:'Strategy explainer',alt:'A mother and child in Malawi, shown as contextual maternal-health imagery'}}),
 make({id:'resource-evidence-to-action',kind:'resource',slug:'from-evidence-to-action',title:'From local evidence to better programme decisions',summary:'How research, monitoring and shared learning are designed to inform delivery, adaptation and health innovation.',programme:'research-innovation',topic:'Research & learning',image:'/images/health-worker.jpg',body:'MCHF’s research programme is designed to generate locally relevant evidence that improves practical public-health decisions. The Strategic Plan identifies operational research, community health assessments and studies of knowledge, attitudes and practices as priorities.\nMonitoring, Evaluation & Learning connects this evidence with delivery. The plan provides for programme frameworks, data collection and analysis, baseline, midline and endline assessments, reviews and evaluations. Findings are intended to improve implementation rather than sit apart from it.\nKnowledge translation makes research useful beyond the study itself. Planned outputs include practical recommendations, research reports, policy briefs and evidence summaries, alongside stakeholder dialogues, learning events and digital dissemination.\nInnovation also requires testing and learning. The strategy proposes practical pilots in community health, digital health and behaviour-change communication, with lessons documented before decisions about wider use.\nThe website distinguishes the research agenda from completed studies. Research findings and tested solutions will be published once their supporting evidence is available.',meta:{format:'HTML',documentType:'Strategy explainer',alt:'A nurse in the newborn unit at Koidu Government Hospital, Sierra Leone, shown as contextual healthcare imagery'}}),
 make({id:'resource-sustainable-systems',kind:'resource',slug:'stronger-systems-for-lasting-health',title:'Stronger systems for lasting health',summary:'Connecting community referrals, frontline capacity and institutional partnerships to more sustainable care.',programme:'health-systems',topic:'Systems & sustainability',image:'/images/hero.jpg',body:'Sustainability is a cross-cutting priority in the MCHF Strategic Plan. The framework favours approaches that communities and local institutions can own and sustain beyond individual project funding.\nCommunity–facility linkages are one part of that ambition. Planned activities include assessing barriers to access, strengthening referral pathways, supporting community-based referral and follow-up, and helping people understand available services.\nFrontline capacity is another. The plan provides for mentorship, coaching, continuing learning and training materials based on identified needs, including support for community health workers and frontline personnel.\nQuality improvement is developed with health authorities and facilities. Strategic activities include service assessments, quality tools, monitoring of delivery challenges and documentation of effective practices.\nPartnerships connect these priorities. Government, universities, civil society, development partners and private-sector organisations are invited to contribute through collaboration, coordination, research and resource mobilisation. Specific partners and achievements will only be named when officially confirmed.',meta:{format:'HTML',documentType:'Strategy explainer',alt:'A mother with children in Sierra Leone, shown as contextual community-health imagery'}}),
 make({id:'contact-official',kind:'contact',slug:'official',title:'Contact MCHF',summary:'Freetown, Sierra Leone',source:'MCHF Memorandum & Articles of Association',meta:{city:'Freetown',country:'Sierra Leone',email:'',phone:'',address:''}}),
 make({id:'page-about',kind:'page',slug:'about',title:'Health equity begins with people.',summary:mission,body:'MCHF brings community action, research, health promotion and stronger services together in one integrated public-health approach. Our strategic framework serves adolescents, young people, women, newborns and children, with particular attention to underserved communities.'}),
];
export const listingRoutes:Record<string,{title:string;summary:string;kinds:string[];eyebrow:string;empty:string}>={
 'our-work':{title:'Purpose into practice.',summary:'Explore MCHF’s projects and initiatives across our five connected programme areas.',kinds:['project'],eyebrow:'OUR WORK',empty:'Projects and initiatives will be published as programme implementation develops.'},
 research:{title:'Evidence that moves health forward.',summary:'Operational research, community insights and learning that inform better programmes and stronger health systems.',kinds:['research'],eyebrow:'RESEARCH & EVIDENCE',empty:'Research studies and findings will appear here as MCHF’s research portfolio develops.'},
 publications:{title:'Knowledge, openly shared.',summary:'Explore the documents that guide our strategy, governance and evidence-based approach.',kinds:['publication','report','resource'],eyebrow:'PUBLICATIONS LIBRARY',empty:'No documents match your filters. Try another topic or programme.'},
 knowledge:{title:'From knowledge to action.',summary:'Practical resources, guidelines and learning products for communities, health workers and partners.',kinds:['resource','publication','report'],eyebrow:'KNOWLEDGE CENTRE',empty:'Knowledge resources will appear as they are reviewed and published.'},
 insights:{title:'A little learning. Every day.',summary:'Ideas, practical perspectives and lessons from MCHF’s public-health work.',kinds:['insight'],eyebrow:'DAILY INSIGHTS',empty:'Daily insights will appear here as the MCHF team publishes them.'},
 news:{title:'Ideas, updates & perspectives.',summary:'Follow the development of MCHF’s programmes, research and institutional work.',kinds:['news'],eyebrow:'NEWS & INSIGHTS',empty:'News and institutional updates will be published here as they become available.'},
 events:{title:'Connect. Exchange. Learn.',summary:'Discover MCHF’s learning events, community dialogues and collaboration opportunities.',kinds:['event'],eyebrow:'NEWS & EVENTS',empty:'No upcoming events have been announced. Please check back for confirmed dates.'},
 stories:{title:'People at the heart of health.',summary:'Community voices, perspectives and experiences across MCHF’s programme areas.',kinds:['story'],eyebrow:'COMMUNITY STORIES',empty:'Community stories will be shared with appropriate consent as programme work develops.'},
 careers:{title:'Bring your purpose to work.',summary:'Opportunities to contribute your skills to equitable, evidence-based public health.',kinds:['career'],eyebrow:'CAREERS',empty:'There are no advertised vacancies at this time. Future opportunities will be posted here.'},
 impact:{title:'Accountable for meaningful change.',summary:'Verified results, evaluation findings and programme learning, with the evidence behind every measure.',kinds:['impact'],eyebrow:'IMPACT & RESULTS',empty:'Data will be published as programme monitoring systems are established.'},
};
export const routeFor=(r:ContentRecord)=>r.kind==='programme'?`/programmes/${r.slug}`:r.kind==='page'?(r.slug==='home'?'/':`/${r.slug}`):r.kind==='publication'&&r.meta.view?r.meta.view:`/${({project:'projects',research:'research',news:'news',insight:'insights',event:'events',story:'stories',career:'careers',resource:'resources',leadership:'profiles',partner:'partners',impact:'results',report:'publications',publication:'publications'} as Record<string,string>)[r.kind]||'resources'}/${r.slug}`;
