export type Lesson={title:string;intro:string;points:[string,string][];image?:string;programme?:string;link?:[string,string]};
export const programmeLessons:Record<string,Lesson>={
 'rmnch':{title:'Understanding care across the life course.',intro:'MCHF’s reproductive, maternal, newborn and child health programme connects stages of life that are often discussed separately. The strategy treats information, community support and access to services as parts of one continuum.',programme:'rmnch',image:'/images/learning-rmnch.jpg',link:['WHO: maternal health','https://www.who.int/health-topics/maternal-health'],points:[['What is a continuum of care?','A connected approach from adolescence and reproductive health through pregnancy, birth and early childhood. Each stage has different needs, and coordination helps people move between relevant services.'],['Why information and choice matter','The plan prioritises youth-friendly information, voluntary and informed family-planning choices, respectful maternal care and community understanding of available services.'],['What a referral connects','Community support helps people understand where services are available. Referral pathways connect this support with appropriate facilities and follow-up, rather than treating outreach as a stand-alone activity.']]},
 'immunization':{title:'Confidence begins with clear information.',intro:'MCHF’s prevention agenda combines vaccine confidence, community engagement and links to routine services. This is an introduction to the programme approach; individual schedules and clinical questions belong with qualified health workers.',programme:'immunization',image:'/images/learning-immunization.jpg',link:['WHO: what is vaccination?','https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-what-is-vaccination'],points:[['Vaccine confidence','Confidence involves trust in information, health workers and the services delivering vaccines. Listening to concerns and discussing them respectfully is part of the strategy.'],['Demand and access work together','Knowing about a service does not guarantee that someone can reach it. Planned work connects communication and mobilisation with service linkages, missed-child follow-up and attention to access barriers.'],['Prevention is a shared effort','The programme also addresses disease-prevention awareness and community preparedness. Accurate information and coordination with health authorities guide this work.']]},
 'community-health':{title:'What it means for communities to lead.',intro:'Community health is shaped by the information people receive, the services they can reach and the decisions they can influence. MCHF’s strategy includes participation, health literacy and equity together.',programme:'community-health',image:'/images/learning-community-health.jpg',points:[['Health literacy','Health information becomes useful when people can understand it, ask questions and connect it with available services. The plan includes accessible materials, community dialogues and trusted peer educators.'],['Meaningful participation','People contribute more than attendance. Youth, women’s groups, local leaders and underserved groups can help identify priorities, shape activities and provide feedback.'],['Equity in practice','Equity recognises that social, economic and geographical barriers are different for different groups. Programme design should identify those barriers and prioritise people who are underserved.']]},
 'research-innovation':{title:'Learning how evidence becomes useful.',intro:'The research programme focuses on locally relevant questions, practical learning and the translation of findings into programme decisions. An agenda describes what will be studied; it is different from a completed finding.',programme:'research-innovation',image:'/images/learning-research-innovation.jpg',points:[['Operational research','Operational research asks practical questions about how programmes and services work. It can help identify implementation challenges and inform improvements in real delivery settings.'],['Monitoring, evaluation and learning','Monitoring follows implementation over time. Evaluation examines a programme more deeply. Learning uses the information to improve decisions, adapt activities and share lessons.'],['Knowledge translation','Reports alone are not the end of research. The strategy includes policy briefs, evidence summaries, dialogues and learning events so findings can inform institutions and communities.']]},
 'health-systems':{title:'The connections behind reliable care.',intro:'A health system includes the people, facilities, coordination and support that make services possible. MCHF’s strategy focuses on strengthening these connections through collaboration with local institutions.',programme:'health-systems',image:'/images/learning-health-systems.jpg',link:['WHO: primary health care','https://www.who.int/health-topics/primary-health-care'],points:[['Frontline capacity','Training, mentorship and continuing learning should respond to identified needs. The plan includes support for community health workers and frontline personnel alongside appropriate learning materials.'],['Community–facility linkages','Referrals, follow-up and awareness of available services help connect communities with facilities. Understanding barriers to access is part of designing useful linkages.'],['Quality and sustainability','Quality improvement uses assessments, tools and learning to address delivery challenges. Sustainability asks whether local communities and institutions can maintain useful improvements over time.']]}
};
const lessons:Record<string,Lesson>={
 search:{title:'Find the source behind an idea.',intro:'Searching the website can help connect a health topic with MCHF’s strategic framework and institutional documents.',points:[['Start with a topic','Use a specific phrase such as community ownership, referrals or operational research.'],['Narrow the context','Programme and content-type filters help distinguish planned activities from resources and published reports.'],['Read the source','Check the original document or article for context before drawing a conclusion from a short result summary.']]},
 privacy:{title:'Share only what an inquiry needs.',intro:'The contact form supports institutional communication. Keeping a message focused also helps protect information about you and other people.',points:[['Necessary information','Provide contact information and context relevant to the inquiry. Avoid adding unrelated personal details.'],['Health information','Do not submit medical records or confidential health details through the institutional inquiry form.'],['Correction or removal','The contact form can be used to ask about access, correction or removal of information you submitted.']]},
 accessibility:{title:'More than one way to reach the information.',intro:'The website presents institutional information in responsive pages as well as original source documents.',points:[['Read in the browser','The strategy and governance pages explain the supplied documents in HTML, alongside original downloads.'],['Use the keyboard','Navigation, form controls and filters can be reached with keyboard controls, with visible focus indicators.'],['Report a barrier','Tell the team which page caused difficulty and describe the issue so it can be reviewed.']]},
 'image-credits':{title:'Understand what an image represents.',intro:'This website uses MCHF-supplied board portraits, licensed documentary photography and original generated illustrations.',points:[['Documentary context','Licensed photographs show real public-health settings. They do not establish that pictured people are MCHF beneficiaries.'],['Educational illustrations','AI-generated artwork visualises programme concepts. It is clearly labelled and does not document a real event.'],['Source and attribution','The credits identify MCHF-supplied portraits, photographers, source pages and reuse licences for documentary assets.']]},
 about:{title:'An integrated foundation, explained.',intro:'MCHF brings five programme areas into one framework. Understanding that structure makes it easier to see how community participation, services and evidence reinforce one another.',points:[['Who the framework serves','Adolescents, young people, women, newborns and children are central to the mission, with particular attention to underserved communities.'],['How the programmes connect','Maternal and child health, prevention, community action, research and health systems are interconnected priorities. They share cross-cutting commitments to inclusion, learning and sustainability.'],['Strategy and delivery','The 2027–2031 plan provides direction. Annual planning defines activities and targets in response to resources, baseline findings, geographical scope and implementation capacity.']]},
 programmes:{title:'Read the programme framework with confidence.',intro:'The five programme areas provide a structure for planning. The intervention and activity counts describe the strategic framework; they are not counts of completed projects or achieved health outcomes.',points:[['Programme area','A broad field of work, such as community health or health-system strengthening, that brings related priorities together.'],['Strategic intervention','A focused approach within a programme area. Each intervention groups practical activity statements from the strategic plan.'],['Priority activity','A planned action that can inform annual work planning. Its scope, targets and resources are refined before implementation.']]},
 'strategic-plan-2027-2031':{title:'A guide to the plan’s learning cycle.',intro:'The strategy combines a long-term direction with regular reviews. This creates opportunities to test assumptions, adjust delivery and make the next annual plan more informed.',points:[['Baseline','A starting assessment against which later progress can be understood. The framework schedules baseline work and programme launch in 2027.'],['Mid-term review','The planned 2029 review provides an opportunity to examine progress, context and priorities while there is still time to adapt.'],['Final evaluation','The planned 2031 evaluation examines the strategic period as a whole. Findings should inform future decisions and be presented with their supporting evidence.']]},
 governance:{title:'Why governance matters to public health.',intro:'Governance connects decision-making authority with responsibility. MCHF’s memorandum aligns five Strategic Executive portfolios with the five programme areas.',points:[['Programme ownership','A defined governance portfolio makes responsibility visible. It helps connect programme direction with institutional oversight.'],['Responsible stewardship','Resources and decisions need accountable management. The supplied articles provide the institutional framework for financial stewardship and conflicts of interest.'],['A clear public record','The board directory pairs MCHF-supplied portraits with each director’s role, portfolio and contact details. The governance framework explains how those responsibilities fit together.']]},
 'how-we-work':{title:'Follow an idea from evidence to action.',intro:'MCHF’s integrated approach links community priorities with evidence, design, implementation and review. Learning remains part of the work throughout the cycle.',points:[['Listen and understand','Community priorities and locally relevant evidence help define the issue before activities are designed.'],['Design and connect','Programme design brings together community engagement, facility linkages and institutional partnerships appropriate to the issue.'],['Review and adapt','Monitoring and evaluation inform learning. Adaptation uses that learning to refine activities and the next planning cycle.']]},
 partnerships:{title:'What a useful partnership can contribute.',intro:'Partnerships are strongest when expertise and responsibilities relate to a clear public-health purpose. The strategy invites collaboration across government, health services, communities, research and development institutions.',points:[['Start with a shared priority','Identify which programme area your organisation can support and the problem you hope to address together.'],['Name the contribution','Contributions may include technical expertise, research, service coordination, learning or institutional support. Specific roles can then be discussed with MCHF.'],['Plan for learning and continuity','Monitoring, coordination and local ownership help partners understand progress and consider how useful improvements can be sustained.']]},
 contact:{title:'Make your inquiry easier to act on.',intro:'A clear institutional inquiry helps the team understand your interest and connect it with the appropriate programme area.',points:[['Explain your purpose','Tell us whether your inquiry concerns a partnership, research, programme information, volunteering or general institutional matters.'],['Add useful context','Include your organisation, the programme area, relevant location and the type of contribution or information you are seeking.'],['Keep personal health details private','Use this form for institutional inquiries. Avoid including medical records or confidential health information; the website does not provide clinical consultations.']]},
 'get-involved':{title:'Match your contribution to a shared priority.',intro:'There are several ways to contribute to the mission. Understanding your interests and skills helps make the first conversation specific.',points:[['Community participation','Local perspectives can inform priorities, programme design and feedback. Meaningful involvement includes listening and shared learning.'],['Technical and research expertise','Research, training, knowledge exchange and programme support can connect specialist skills with the five strategic programme areas.'],['Institutional collaboration','Organisations can explore joint programmes, coordination and responsible support. Available opportunities and roles require confirmation by MCHF.']]},
 'our-work':{title:'Understand the difference between a plan and a project.',intro:'A strategic priority sets a direction. A confirmed project brings that direction into a defined implementation context with agreed responsibilities and resources.',points:[['Purpose and scope','A useful project description explains the issue, intended participants, programme area and where the work takes place.'],['Activities and responsibilities','Implementation details describe what will happen, who is responsible and how community and institutional partners contribute.'],['Evidence and learning','Project reporting should distinguish activities delivered from outcomes observed, and explain the evidence behind any claim.']]},
 impact:{title:'How to read a result responsibly.',intro:'A result is more useful when its meaning and evidence are visible. MCHF’s website will present verified indicators with the context needed to interpret them.',points:[['Outputs and outcomes','Outputs describe work delivered, such as an activity or learning product. Outcomes describe changes that follow. One does not automatically demonstrate the other.'],['Definitions and sources','Look for the indicator definition, data source, reporting period, programme and methodology. These explain what was actually measured.'],['Context and limitations','A baseline, geographical scope and known limitations help readers understand a result. Strategic activity counts describe planned work rather than achieved outcomes.']]},
 knowledge:{title:'Choose the right type of learning resource.',intro:'This library brings together institutional documents and strategy explainers. Different formats answer different questions.',points:[['Strategy documents','Use the strategic plan to understand mission, programme priorities, implementation and review. Use the memorandum to understand governance.'],['Strategy explainers','Short educational articles unpack concepts in the supplied documents. They describe the framework and should not be read as completed research findings.'],['Research and reports','As these become available, consider the question, methods, date, findings and limitations before applying a conclusion in another context.']]},
 news:{title:'Read institutional updates in context.',intro:'Updates will describe confirmed developments in the Foundation’s work. The strategic framework remains available while the news portfolio develops.',points:[['An announcement','An announcement describes a confirmed development or decision. It should identify what has changed and when.'],['An insight','An insight explains an idea or lesson. It should make the underlying source or experience clear.'],['A result','A claim about programme results needs supporting evidence and context. Planned priorities are distinct from completed work.']]},
 events:{title:'Learning happens through exchange.',intro:'The strategy includes community dialogues, stakeholder discussions and learning events as ways to share knowledge and strengthen participation.',points:[['Community dialogue','A space to hear local priorities, questions and perspectives, with attention to inclusion and participation.'],['Stakeholder learning','Institutions can exchange evidence, practical experience and ideas for programme improvement.'],['Confirmed participation','Dates, venues, organisers and registration details will be published when an event is confirmed. No current listing should be treated as an invitation.']]},
 stories:{title:'Community stories deserve care.',intro:'Stories can help people understand lived experience. They should preserve dignity and remain clearly separate from evidence used to measure programme results.',points:[['Voice and consent','People should understand how their story will be shared and have meaningful choice about participation.'],['Context matters','A story describes one perspective in a specific setting. It should not be presented as evidence of a programme-wide outcome.'],['Dignity in representation','Respectful language and imagery avoid stereotypes. The documentary photographs on this site provide context and do not depict confirmed MCHF beneficiaries.']]},
 careers:{title:'Skills that connect with the mission.',intro:'MCHF’s programme framework brings together community engagement, public-health delivery, research and institutional coordination. Vacancies will be advertised only when confirmed.',points:[['Community and communication','Listening, accessible communication and inclusive participation support community-centred programme design.'],['Evidence and learning','Research, monitoring, evaluation and knowledge translation help programmes understand implementation and improve decisions.'],['Coordination and accountability','Reliable planning, partnership coordination and responsible stewardship support effective institutional work.']]}
};
for(const [key,programme] of Object.entries({about:'rmnch',programmes:'community-health','strategic-plan-2027-2031':'health-systems',governance:'health-systems','how-we-work':'health-systems',partnerships:'health-systems',contact:'community-health','get-involved':'community-health','our-work':'health-systems',impact:'research-innovation',knowledge:'research-innovation',news:'community-health',events:'community-health',stories:'community-health',careers:'health-systems'})){lessons[key].image=programmeLessons[programme].image;}
export function lessonFor(path:string):Lesson|undefined {
 if(path.startsWith('programmes/'))return programmeLessons[path.split('/')[1]];
 if(path==='research')return programmeLessons['research-innovation'];
 if(path.startsWith('about/'))return lessons.governance;
 if(path==='publications')return lessons.knowledge;
 if(path.startsWith('audiences/')){const slug=path.split('/')[1];return programmeLessons[slug==='communities'?'community-health':slug==='researchers'||slug==='academic-institutions'?'research-innovation':slug==='health-institutions'?'health-systems':'community-health'];}
 if(path==='resources/community-ownership-in-practice')return programmeLessons['community-health'];
 if(path==='resources/from-evidence-to-action')return programmeLessons['research-innovation'];
 if(path==='resources/stronger-systems-for-lasting-health')return programmeLessons['health-systems'];
 if(path.startsWith('resources/understanding-'))return programmeLessons[path.replace('resources/understanding-','')];
 if(path.startsWith('resources/'))return lessons.knowledge;
 return lessons[path];
}

const guideExamples:Record<string,string>={
 rmnch:'Consider a person moving from youth health information to reproductive-health services, and later to pregnancy and early-childhood care. A connected programme asks whether information is understandable, services are known and transitions between services are supported. This example illustrates the continuum described in the strategy; it is not an account of an MCHF case or project.',
 immunization:'Consider a caregiver who has heard conflicting information and is unsure how to reach a routine service. Communication alone addresses only one part of the situation. Respectful discussion with a qualified health worker, clear service information and attention to practical access barriers connect confidence with access. The specific vaccination schedule and suitability of a vaccine should be discussed with a qualified health worker.',
 'community-health':'Consider a proposed community outreach activity. A community-centred design asks whose priorities informed it, whether young people and underserved groups could contribute, and how feedback will be heard. Attendance alone does not show that people influenced a decision. The strategy’s participation and inclusion commitments encourage programmes to consider both reach and voice.',
 'research-innovation':'Consider an outreach activity that reaches fewer people than expected. An operational research question might explore which implementation barriers explain that pattern. Monitoring helps describe delivery; research can examine why it happens; learning helps the team decide what to adjust. Any conclusion still needs appropriate methods and evidence, rather than an assumption based on one observation.',
 'health-systems':'Consider a community member who learns about a service but is unsure how to reach the right facility or obtain follow-up. A system perspective asks whether service information, referral processes, health-worker capacity and coordination work together. The example shows why a useful connection matters alongside an individual activity; it does not describe a completed MCHF intervention.'
};
const guideQuestions:Record<string,string>={
 rmnch:'Which stages of care are connected in the programme design? How do people learn about the services available to them? What information would show whether a referral pathway is functioning?',
 immunization:'What concerns are community members expressing? Are reliable service details accessible? Which practical barriers should be discussed with health-service partners?',
 'community-health':'Whose voice is missing from a discussion? How will people know that their feedback was considered? Which barriers could prevent a group from taking part?',
 'research-innovation':'What practical question is being asked? Which evidence could answer it? How would a finding change a programme decision, and what limitations should readers know?',
 'health-systems':'Where does a service connection break down? Which organisations need to coordinate? How could local institutions maintain an improvement over time?'
};
export function learningGuideBody(slug:string,lesson:Lesson){return [lesson.intro,...lesson.points.map(([t,d])=>t+' — '+d),'An example to think through — '+guideExamples[slug],'Questions for discussion — '+guideQuestions[slug],'Reading the framework — These concepts explain MCHF’s strategic direction for 2027–2031. They are not claims of completed activities or verified outcomes. Annual planning refines implementation in response to baseline findings, confirmed resources, geographical scope and capacity.'].join('\n');}
