import { sqliteTable,text,integer,index } from 'drizzle-orm/sqlite-core';
export const content=sqliteTable('content',{id:text('id').primaryKey(),kind:text('kind').notNull(),slug:text('slug').notNull(),title:text('title').notNull(),summary:text('summary').notNull().default(''),body:text('body').notNull().default(''),status:text('status').notNull().default('draft'),programme:text('programme').notNull().default(''),year:text('year').notNull().default(''),topic:text('topic').notNull().default(''),location:text('location').notNull().default(''),image:text('image').notNull().default(''),file:text('file').notNull().default(''),source:text('source').notNull().default(''),meta:text('meta').notNull().default('{}'),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('content_status_kind').on(t.status,t.kind)]);
export const members=sqliteTable('members',{id:text('id').primaryKey(),email:text('email').notNull().unique(),role:text('role').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()});
export const inquiries=sqliteTable('inquiries',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),organization:text('organization').notNull().default(''),phone:text('phone').notNull().default(''),type:text('type').notNull(),interest:text('interest').notNull().default(''),message:text('message').notNull(),status:text('status').notNull().default('new'),createdAt:text('created_at').notNull()});
export const media=sqliteTable('media',{id:text('id').primaryKey(),key:text('key').notNull(),filename:text('filename').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),alt:text('alt').notNull().default(''),uploadedBy:text('uploaded_by').notNull(),createdAt:text('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),recordId:text('record_id').notNull(),details:text('details').notNull(),createdAt:text('created_at').notNull()});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});

export const analyticsEvents=sqliteTable('analytics_events',{id:text('id').primaryKey(),path:text('path').notNull(),visitorHash:text('visitor_hash').notNull(),referrer:text('referrer').notNull().default(''),device:text('device').notNull(),country:text('country').notNull().default(''),duration:integer('duration').notNull().default(0),occurredAt:text('occurred_at').notNull(),lastSeen:text('last_seen').notNull()},t=>[index('analytics_occurred').on(t.occurredAt),index('analytics_last_seen').on(t.lastSeen)]);
