'use client';

import {Eye,Users,FileText,Clock,Plus,ArrowUpRight,BarChart3,Newspaper} from 'lucide-react';
import {ContentRecord,routeFor} from '@/lib/content';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';

export type AudienceReport={
  summary:{visitorsToday:number;viewsToday:number;visitorsPeriod:number;viewsPeriod:number;activeNow:number;averageEngagement:number};
  daily:{date:string;visitors:number;views:number}[];
  pages:{path:string;views:number;visitors:number}[];
  referrers:{source:string;views:number}[];
  devices:{device:string;views:number}[];
  countries:{country:string;views:number}[];
};

export function AudienceChart({report}:{report:AudienceReport|null}){
  if(!report)return <div className='audience-unavailable'><BarChart3 size={30}/><h3>Visitor reports are being connected</h3><p>Traffic will appear here once visitor tracking is available.</p></div>;
  if(!report.summary.viewsPeriod)return <div className='audience-unavailable'><BarChart3 size={30}/><h3>Your audience story starts here</h3><p>Visit a public page to record the first page view. Staff dashboard visits are excluded.</p></div>;
  return <div className='audience-chart' role='img' aria-label={'Daily traffic chart: '+report.summary.visitorsPeriod+' daily visitors and '+report.summary.viewsPeriod+' page views across the selected period.'}><ResponsiveContainer width='100%' height={265}><AreaChart data={report.daily} margin={{top:15,right:15,left:-18,bottom:0}}><defs><linearGradient id='mchf-audience-fill' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stopColor='#478662' stopOpacity={.25}/><stop offset='100%' stopColor='#478662' stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke='#e7ece8' vertical={false}/><XAxis dataKey='date' tickFormatter={v=>new Date(v+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Africa/Freetown'})} tick={{fontSize:11,fill:'#718078'}} axisLine={false} tickLine={false} minTickGap={35}/><YAxis allowDecimals={false} tick={{fontSize:11,fill:'#718078'}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>new Date(String(v)+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',timeZone:'Africa/Freetown'})}/><Area type='monotone' dataKey='views' name='Page views' stroke='#b8944c' strokeWidth={2} fill='transparent'/><Area type='monotone' dataKey='visitors' name='Daily visitors' stroke='#478662' strokeWidth={3} fill='url(#mchf-audience-fill)'/></AreaChart></ResponsiveContainer></div>;
}

export default function AdminOverview({canManage,canCreate,records,inquiries,report,loading,onCreate,onView}:{canManage:boolean;canCreate:(kind:string)=>boolean;records:ContentRecord[];inquiries:number;report:AudienceReport|null;loading:boolean;onCreate:(kind:string)=>void;onView:(tab:string)=>void}){
  const published=records.filter(r=>r.status==='published'),drafts=records.filter(r=>['draft','review'].includes(r.status));
  const metrics=[{label:'Visitors today',value:report?.summary.visitorsToday,icon:Users,note:'Estimated unique daily visitors'},{label:'Page views today',value:report?.summary.viewsToday,icon:Eye,note:'Public pages only'},{label:'Published content',value:published.length,icon:FileText,note:'Across your website'},{label:'Drafts & reviews',value:drafts.length,icon:Clock,note:'Ready for your attention'}];
  return <div className='dashboard-overview'><div className='dashboard-metrics'>{metrics.map(({label,value,icon:Icon,note})=><article key={label}><div><span>{label}</span><Icon size={19}/></div><strong>{loading?'—':value??'—'}</strong><p>{note}</p></article>)}</div><div className='dashboard-primary'><section className='dashboard-panel'><div className='dashboard-panel-heading'><div><span className='eyebrow'>YOUR REACH</span><h2>Audience at a glance</h2></div>{canManage&&<button onClick={()=>onView('analytics')}>View report <ArrowUpRight size={15}/></button>}</div><div className='audience-legend'><span>Daily visitors</span><span>Page views</span><small>Last 30 days</small></div><AudienceChart report={report}/></section><section className='dashboard-panel dashboard-publish'><span className='eyebrow'>SHARE WHAT MATTERS</span><h2>Keep your community informed.</h2><p>Publish an update, share a learning insight, or announce your next event.</p><button disabled={!canCreate('news')} className='button teal' onClick={()=>onCreate('news')}><Plus size={17}/> Write an update</button><button disabled={!canCreate('insight')} className='dashboard-quick-action' onClick={()=>onCreate('insight')}><Newspaper size={18}/><span>Publish a daily insight</span><Plus size={16}/></button><button disabled={!canCreate('event')} className='dashboard-quick-action' onClick={()=>onCreate('event')}><Clock size={18}/><span>Announce an event</span><Plus size={16}/></button>{canManage&&<div className='dashboard-inquiry-note'><strong>{inquiries}</strong> received inquiries <button onClick={()=>onView('inquiries')}>Open inbox</button></div>}</section></div><div className='dashboard-secondary'><section className='dashboard-panel'><div className='dashboard-panel-heading'><h2>Publishing desk</h2><button onClick={()=>onView('content')}>All content</button></div>{drafts.length?<div className='dashboard-recent'>{drafts.slice(0,5).map(r=><div key={r.id}><FileText size={18}/><div><strong>{r.title}</strong><span>{r.kind} · {r.status}</span></div></div>)}</div>:<div className='dashboard-small-empty'><Clock size={24}/><h3>Your publishing desk is clear.</h3><p>New drafts and review requests will appear here.</p></div>}</section><section className='dashboard-panel'><div className='dashboard-panel-heading'><h2>Recently published</h2><button onClick={()=>onView('content')}>Manage content</button></div><div className='dashboard-recent'>{published.filter(r=>!['activity','intervention','setting','contact'].includes(r.kind)).slice(0,5).map(r=><a href={routeFor(r)} target='_blank' rel='noreferrer' key={r.id}><FileText size={18}/><div><strong>{r.title}</strong><span>{r.kind}</span></div><ArrowUpRight size={15}/></a>)}</div></section></div></div>;
}
