import Link from 'next/link';
import {MapPin,Mail,Phone} from 'lucide-react';
import {ContentRecord,programmes,routeFor} from '@/lib/content';
import {Breadcrumbs} from './common';

export function BoardContacts({record:r}:{record:ContentRecord}){return <div className='board-contacts'>{r.location&&<p><MapPin size={16}/><span>{r.location}</span></p>}{r.meta.email&&<a href={'mailto:'+r.meta.email}><Mail size={16}/><span>{r.meta.email}</span></a>}{r.meta.phone&&<a href={'tel:'+r.meta.phone}><Phone size={16}/><span>{r.meta.phone}</span></a>}</div>}
export function BoardDirectory({records}:{records:ContentRecord[]}){return <div className='board-grid'>{records.map(r=><article className='board-card' key={r.id}><Link href={routeFor(r)} className='board-photo-link' aria-label={'View '+r.title+'’s profile'}><img src={r.image} alt={r.meta.alt||r.title} style={{objectPosition:r.meta.photoPosition||'50% 35%'}} loading='lazy'/>{r.meta.boardRole&&<span className='board-role-tag'>{r.meta.boardRole}</span>}</Link><div className='board-card-content'><span className='eyebrow'>{r.meta.position||'Board member'}</span><h3><Link href={routeFor(r)}>{r.title}</Link></h3><p className='board-portfolio'>{r.meta.portfolio||r.summary}</p><BoardContacts record={r}/><Link href={routeFor(r)} className='board-profile-link'>View profile</Link></div></article>)}</div>}
export function BoardPreview({records}:{records:ContentRecord[]}){if(!records.length)return null;return <section className='board-preview inner-section'><div><span className='eyebrow'>THE PEOPLE BEHIND THE FOUNDATION</span><h2>Meet our Board of Directors.</h2><p>Five programme portfolios, each with a dedicated governance owner.</p><Link className='board-profile-link' href='/about/leadership'>Explore the board</Link></div><div className='board-preview-portraits'>{records.map(r=><Link key={r.id} href={routeFor(r)} aria-label={'View '+r.title+'’s profile'}><img src={r.image} alt={r.title} style={{objectPosition:r.meta.photoPosition||'50% 35%'}} loading='lazy'/><span>{r.title}</span></Link>)}</div></section>}
export function BoardProfile({record:r}:{record:ContentRecord}){const programme=programmes.find(p=>p.slug===r.programme);return <><section className='board-profile-hero'><div className='container'><Breadcrumbs title={r.title} parent={['Board of Directors','/about/leadership']}/><div className='board-profile-layout'><figure><img src={r.image} alt={r.meta.alt||r.title} style={{objectPosition:r.meta.photoPosition||'50% 35%'}}/><figcaption>{r.meta.position}{r.meta.boardRole?' · '+r.meta.boardRole:''}</figcaption></figure><div><span className='eyebrow'>MCHF BOARD OF DIRECTORS</span><h1>{r.title}</h1><p className='board-profile-position'>{r.meta.position}{r.meta.boardRole?' · '+r.meta.boardRole:''}</p><div className='board-profile-portfolio'><span className='eyebrow'>STRATEGIC PORTFOLIO</span><h2>{r.meta.portfolio||r.summary}</h2>{r.meta.portfolioSummary&&<p>{r.meta.portfolioSummary}</p>}</div><BoardContacts record={r}/></div></div></div></section><section className='section'><div className='container board-profile-body'><div><span className='eyebrow'>BOARD PORTFOLIO</span><h2>A programme with clear responsibility.</h2></div><div>{r.body.split('\n').filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}{r.meta.biography&&<p>{r.meta.biography}</p>}{programme&&<div className='board-programme-link'><span className='eyebrow'>RELATED PROGRAMME</span><h3>{programme.title}</h3><p>{programme.subtitle}.</p><Link className='board-profile-link' href={'/programmes/'+programme.slug}>Explore the programme</Link></div>}<Link className='board-profile-link' href='/about/leadership'>Back to the Board of Directors</Link></div></div></section></>}
