'use client';
import {useState,useEffect} from 'react';
import {Search,X} from 'lucide-react';
import {ContentRecord,programmes,routeFor} from '@/lib/content';
import {RecordCard,EmptyState} from './common';
import Link from 'next/link';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Pagination,PaginationContent,PaginationItem,PaginationPrevious,PaginationNext} from '@/components/ui/pagination';
export function FilterSelect({value,onChange,label,options}:{value:string;onChange:(v:string)=>void;label:string;options:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className='filter-select'><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem value={v} key={v}>{t}</SelectItem>)}</SelectContent></Select>}
export default function Collection({records,empty,search=false,initialQuery='',initialProgramme='all',initialType='all'}:{records:ContentRecord[];empty:string;search?:boolean;initialQuery?:string;initialProgramme?:string;initialType?:string}){const[q,setQ]=useState(initialQuery),[programme,setProgramme]=useState(initialProgramme),[type,setType]=useState(initialType),[year,setYear]=useState('all'),[topic,setTopic]=useState('all'),[location,setLocation]=useState('all'),[page,setPage]=useState(1);useEffect(()=>{setPage(1)},[q,programme,type,year,topic,location]);const types=[...new Set(records.map(r=>r.kind))],years=[...new Set(records.map(r=>r.year).filter(Boolean))],topics=[...new Set(records.map(r=>r.topic).filter(Boolean))],locations=[...new Set(records.map(r=>r.location).filter(Boolean))];const filtered=records.filter(r=>(!q||[r.title,r.summary,r.body,r.topic,r.programme].join(' ').toLowerCase().includes(q.toLowerCase()))&&(programme==='all'||r.programme===programme)&&(type==='all'||r.kind===type)&&(year==='all'||r.year===year)&&(topic==='all'||r.topic===topic)&&(location==='all'||r.location===location));
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_mchf_library',description:'Filter visible MCHF content by search phrase and programme.',inputSchema:{type:'object',properties:{query:{type:'string'},programme:{type:'string',enum:['all',...programmes.map(p=>p.slug)]}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:any){if(typeof input?.query!=='string'||input.query.length>200||(input.programme&&!['all',...programmes.map(p=>p.slug)].includes(input.programme)))throw new Error('Invalid filter');setQ(input.query);setProgramme(input.programme||'all');setPage(1);return {query:input.query,programme:input.programme||'all'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort()},[]);
return <><div className='library-tools'><div className='library-search'><Search size={19}/><input aria-label={search?'Search MCHF':'Search this collection'} value={q} onChange={e=>setQ(e.target.value)} placeholder={search?'Search programmes, research, resources…':'Search by title, keyword or topic…'}/>{q&&<button aria-label='Clear search' onClick={()=>setQ('')}><X size={16}/></button>}</div><div className='filters'><FilterSelect label='Programme' value={programme} onChange={setProgramme} options={[['all','All programmes'],...programmes.map(p=>[p.slug,p.shortTitle] as [string,string])]}/><FilterSelect label='Content type' value={type} onChange={setType} options={[['all','All content types'],...types.map(t=>[t,t.charAt(0).toUpperCase()+t.slice(1)] as [string,string])]}/><FilterSelect label='Year' value={year} onChange={setYear} options={[['all','All years'],...years.map(y=>[y,y] as [string,string])]}/>{topics.length>0&&<FilterSelect label='Topic' value={topic} onChange={setTopic} options={[['all','All topics'],...topics.map(y=>[y,y] as [string,string])]}/>}<FilterSelect label='Location' value={location} onChange={setLocation} options={[['all','All locations'],...locations.map(y=>[y,y] as [string,string])]}/></div></div><div className='results-count' aria-live='polite'>{filtered.length} {filtered.length===1?'result':'results'}{q?` for “${q}”`:''}<button onClick={()=>{setQ('');setProgramme('all');setType('all');setYear('all');setTopic('all');setLocation('all')}}>Reset filters</button></div>{filtered.length?<div className={search?'search-results':'library-results'}>{filtered.slice((page-1)*8,page*8).map(r=>search?<article className='search-result' key={r.id}><span className='eyebrow'>{r.kind} {r.year&&' · '+r.year}</span><h3><Link href={['intervention','activity'].includes(r.kind)?`/programmes/${r.programme}`:routeFor(r)}>{r.title}</Link></h3><p>{r.summary}</p>{r.programme&&<span className='meta'>{programmes.find(p=>p.slug===r.programme)?.shortTitle}</span>}</article>:<RecordCard key={r.id} record={r}/>)}</div>:<EmptyState title={q||programme!=='all'||type!=='all'?'No matching results.':'Updates will appear here.'} text={empty} href='/strategic-plan-2027-2031'/>}{filtered.length>8&&<Pagination className='pagination'><PaginationContent><PaginationItem><PaginationPrevious href='#results' aria-disabled={page===1} onClick={e=>{e.preventDefault();setPage(Math.max(1,page-1))}}/></PaginationItem><PaginationItem><span className='page-count'>Page {page} of {Math.ceil(filtered.length/8)}</span></PaginationItem><PaginationItem><PaginationNext href='#results' aria-disabled={page*8>=filtered.length} onClick={e=>{e.preventDefault();setPage(Math.min(Math.ceil(filtered.length/8),page+1))}}/></PaginationItem></PaginationContent></Pagination>}</>}
