import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Download,FileText,ChevronRight,BookOpen} from 'lucide-react';
import {PageVisual} from './page-visuals';
import {ContentRecord,routeFor,programmes} from '@/lib/content';
export function SectionHead({eyebrow,title,text,href,label}:{eyebrow:string;title:string;text?:string;href?:string;label?:string}){return <div className='section-head'><div><span className='eyebrow'>{eyebrow}</span><h2>{title.split('<br/>').map((line,i)=><span key={i}>{i>0&&<br/>}{line}</span>)}</h2></div>{href?<Link className='text-link' href={href}>{label||'Explore more'}<ArrowRight size={16}/></Link>:text?<p>{text}</p>:null}</div>}
export function Breadcrumbs({title,parent}:{title:string;parent?:[string,string]}){return <nav className='breadcrumbs' aria-label='Breadcrumb'><Link href='/'>Home</Link><ChevronRight size={12}/>{parent&&<><Link href={parent[1]}>{parent[0]}</Link><ChevronRight size={12}/></>}<span aria-current='page'>{title}</span></nav>}
export type PageHeroProps={title:string;summary:string;eyebrow:string;parent?:[string,string];image?:string;visual?:PageVisual};
export function PageHero({title,summary,eyebrow,parent,image,visual}:PageHeroProps){const photo=image||visual?.image;const samePhoto=photo===visual?.image;const illustration=photo?.includes('/learning-');return <section className={'page-hero hero-tone-'+(visual?.tone||'blue')+' '+(photo?'with-image':'')}><div className='container'><Breadcrumbs title={eyebrow.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())} parent={parent}/><div className='page-hero-inner'><div><span className='eyebrow'>{eyebrow}</span><h1>{title}</h1><p>{summary}</p></div>{photo&&<figure className='page-hero-photo'><img src={photo} alt={illustration?'AI-generated educational illustration for '+title:samePhoto&&visual?.alt?visual.alt:'Documentary public-health context'}/><figcaption>{illustration?'Understanding public health':samePhoto&&visual?.caption?visual.caption:'Public health, with people at the centre'}<span>{illustration?'AI-generated educational illustration':'Contextual photography'}</span></figcaption></figure>}</div></div></section>}
export function ProgrammeGrid({records}:{records?:ContentRecord[]}={}){const list=records?records.filter(r=>r.kind==='programme').map((r,i)=>({...programmes.find(p=>p.slug===r.slug),slug:r.slug,number:String(i+1).padStart(2,'0'),title:r.title,subtitle:r.summary,interventions:r.meta.interventions||[]})):programmes;return <div className='programme-grid'>{list.map(p=><Link key={p.slug} className='programme-card' href={'/programmes/'+p.slug}>{p.image&&<img className='programme-card-photo' src={p.image} alt={p.shortTitle||p.title} loading='lazy'/>}<span className='programme-number'>{p.number}</span><h3>{p.title}</h3><p>{p.subtitle}</p><ul className='programme-topics'>{p.interventions.slice(0,3).map((x:any)=><li key={x.title}>{x.title}</li>)}</ul><span className='programme-meta'>{p.interventions.length} strategic interventions</span><span className='text-link'>Explore programme <ArrowUpRight size={17}/></span></Link>)}</div>}
export function DocumentCard({record:r}:{record:ContentRecord}){return <article className='document-card'>{r.image?<img className='document-photo' src={r.image} alt={r.meta.alt||r.title} loading='lazy'/>:<div className='document-symbol'><FileText size={28} strokeWidth={1.2}/><span>{r.meta.format||'DOCUMENT'}</span></div>}<div><span className='eyebrow'>{r.meta.documentType||r.kind}{r.year?' · '+r.year:''}</span><h3><Link href={routeFor(r)}>{r.title}</Link></h3><p>{r.summary}</p><div className='document-actions'><Link href={routeFor(r)}>Read online <ArrowUpRight size={14}/></Link>{r.file&&<a href={r.file} download>Download {r.meta.format||'file'} <Download size={14}/></a>}</div></div></article>}
export function RecordCard({record:r}:{record:ContentRecord}){if(['publication','report','resource'].includes(r.kind))return <DocumentCard record={r}/>;return <article className='record-card'>{r.image&&<img src={r.image} alt={r.meta.alt||r.title} loading='lazy'/>}<div><span className='eyebrow'>{r.topic||r.kind}{r.year?' · '+r.year:''}</span><h3><Link href={routeFor(r)}>{r.title}</Link></h3><p>{r.summary}</p>{r.location&&<span className='meta'>{r.location}</span>}<Link className='text-link' href={routeFor(r)}>Read more <ArrowUpRight size={15}/></Link></div></article>}
export function EmptyState({title='More to come.',text,href,label}:{title?:string;text:string;href?:string;label?:string}){return <div className='empty-state'><BookOpen size={29} strokeWidth={1.3}/><h3>{title}</h3><p>{text}</p>{href&&<Link className='text-link' href={href}>{label||'Explore our strategy'}<ArrowRight size={16}/></Link>}</div>}
