import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Heart,Users,ShieldCheck,Lightbulb,Microscope,Check,BookOpen,Stethoscope,Network,ClipboardCheck} from 'lucide-react';
import {values,priorities,ContentRecord,routeFor} from '@/lib/content';
import {SectionHead} from './common';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';

export function MissionFeature(){return <section className='section mission-feature'><div className='container mission-feature-grid'><div><span className='eyebrow'>WHY WE EXIST</span><h2>A fair chance at health.<br/><em>At every stage of life.</em></h2><p>Health equity begins with understanding the different needs of adolescents, young people, women, newborns and children. MCHF connects prevention, care, community action and research to help meet those needs.</p><Link href='/about' className='text-link'>Get to know MCHF <ArrowUpRight size={17}/></Link></div><div className='mission-panel'><span className='eyebrow'>OUR COMMITMENT</span><h3>Equitable. Evidence-based.<br/>Integrated. Sustainable.</h3><p>Our strategic objective is to contribute to better, more equitable health outcomes by 2031, with particular attention to underserved communities.</p><div className='life-stages'>{['Adolescents','Young people','Women','Newborns','Children'].map(t=><span key={t}>{t}</span>)}</div><span className='mission-source'>Guided by the MCHF Strategic Plan 2027–2031</span></div></div></section>}

export function CommunityFeature(){return <section className='community-feature'><div className='container community-feature-grid'><div className='community-photo'><img src='/images/mother-child.jpg' alt='A mother and young child in Malawi; contextual African maternal-health photography' loading='lazy'/><span>COMMUNITY VOICES. SHARED RESPONSIBILITY.</span></div><div className='community-copy'><span className='eyebrow'>HEALTH THAT BELONGS TO EVERYONE</span><h2>Communities are<br/>partners in change.</h2><p>MCHF’s strategy recognises communities as owners and drivers of their health outcomes. Local priorities, lived experience and participation help shape practical solutions.</p><ul><li><Check size={17}/><span><strong>Meaningful youth participation</strong>Adolescents and young people contribute to programme design, communication and evaluation.</span></li><li><Check size={17}/><span><strong>Health information people can use</strong>Culturally appropriate materials, peer education and trusted community champions support informed decisions.</span></li><li><Check size={17}/><span><strong>More inclusive access</strong>Programme design considers the social, geographical and economic barriers facing underserved groups.</span></li></ul><Link className='text-link' href='/programmes/community-health'>Explore community health & equity <ArrowUpRight size={17}/></Link></div></div></section>}

export function ValuesFeature(){const icons=[Heart,Microscope,ShieldCheck,Lightbulb,Users];return <section className='section values-feature'><div className='container'><SectionHead eyebrow='OUR VALUES IN PRACTICE' title='The commitments behind our work.' href='/about' label='Our mission & values'/><div className='values-feature-grid'>{values.map(([t,d],i)=>{const Icon=icons[i];return <article key={t}><Icon size={27} strokeWidth={1.5}/><h3>{t}</h3><p>{d}</p></article>})}</div></div></section>}

export function StrategyInsights({records}:{records:ContentRecord[]}){const resources=records.filter(r=>r.kind==='resource'&&r.meta.documentType==='Strategy explainer');return <section className='section strategy-insights'><div className='container'><SectionHead eyebrow='INSIDE OUR STRATEGY' title='Understand the thinking behind the work.' href='/knowledge' label='More knowledge & resources'/><div className='insight-grid'>{resources.map((r,i)=><article className={'insight-card insight-'+i} key={r.id}><Link href={routeFor(r)} className='insight-photo'><img src={r.image} alt={r.meta.alt||r.title} loading='lazy'/><span>STRATEGY EXPLAINER</span></Link><div><span className='eyebrow'>{r.topic}</span><h3><Link href={routeFor(r)}>{r.title}</Link></h3><p>{r.summary}</p><Link className='text-link' href={routeFor(r)}>Read the explainer <ArrowUpRight size={16}/></Link></div></article>)}</div></div></section>}

const faq=[['Who does MCHF serve?','MCHF’s strategic framework focuses on adolescents, young people, women, newborns and children, with particular attention to underserved, vulnerable and marginalised communities.'],['How do the five programme areas connect?','Maternal and child health, immunization, community empowerment, research and health-system strengthening reinforce one another. Research informs delivery; community participation shapes priorities; service linkages and partnerships support sustainability.'],['What does the 2027–2031 strategy include?','The supplied strategic plan sets out five programme areas, 26 key strategic interventions and 129 mapped priority activities, alongside indicators, target directions, timelines and accountable teams. Specific numerical targets are refined through annual planning.'],['How will MCHF measure progress?','The plan provides for baseline assessment and launch in 2027, quarterly and annual reviews, a mid-term strategic review in 2029 and a final strategic evaluation in 2031. Monitoring findings and community feedback inform programme adaptation.'],['How can institutions collaborate with MCHF?','The strategy invites joint programmes, research, technical collaboration and shared investment with government, universities, civil society, development partners and communities. The partnership inquiry form is the starting point for a conversation.']];
export function StrategyFAQ(){return <section className='inner-section strategy-faq'><SectionHead eyebrow='UNDERSTANDING MCHF' title='A few useful answers.'/><Accordion type='single' collapsible>{faq.map(([q,a],i)=><AccordionItem value={'faq-'+i} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion><p className='source-note'>Based on the supplied MCHF Strategic Plan and Memorandum & Articles of Association.</p></section>}

const focuses={research:{eyebrow:'OUR RESEARCH AGENDA',title:'Local questions. Useful evidence.',intro:'The strategic plan identifies research priorities that connect directly to programme delivery and community needs.',cards:[['Operational & community research','Identify evidence gaps through health assessments, operational research and studies of knowledge, attitudes and practices.',Microscope],['Monitoring, evaluation & learning','Use baseline, midline and endline assessments, programme data and reviews to understand progress and improve implementation.',ClipboardCheck],['Knowledge into practice','Translate findings into practical recommendations, evidence summaries, policy briefs and shared learning with institutions and communities.',BookOpen]]},delivery:{eyebrow:'OUR IMPLEMENTATION PRIORITIES',title:'How the strategy becomes action.',intro:'These are planned ways of working drawn from the 2027–2031 framework. Confirmed project details will be published separately.',cards:[['Community education & engagement','Health literacy, culturally appropriate information, youth participation and peer support are central to the planned programme approach.',Users],['Stronger links to care','Community-to-facility referral, follow-up and awareness of available services connect health promotion with practical access to care.',Stethoscope],['Capacity & collaboration','Mentorship, quality improvement and institutional partnerships support frontline health workers and sustainable local systems.',Network]]},accountability:{eyebrow:'WHAT ACCOUNTABILITY LOOKS LIKE',title:'A clear framework for measuring progress.',intro:'The implementation matrix connects planned activities to evidence, annual targets and responsibility. Outcome data will be published when verified.',cards:[['Defined indicators','Each strategic intervention has a key indicator, target direction, implementation timeline and responsible team.',ClipboardCheck],['Realistic annual targets','Targets are set against baseline findings, confirmed resources, community needs, geographical scope and implementation capacity.',ShieldCheck],['Learning and review','Quarterly and annual reviews, the 2029 mid-term review and the 2031 final evaluation support adaptation and institutional accountability.',BookOpen]]}};
export function StrategicFocus({variant}:{variant:keyof typeof focuses}){const f=focuses[variant];return <section className={'inner-section strategic-focus focus-'+variant}><SectionHead eyebrow={f.eyebrow} title={f.title}/><p className='focus-intro'>{f.intro}</p><div className='focus-grid'>{f.cards.map(([t,d,I])=>{const Icon=I as typeof Users;return <article key={String(t)}><Icon size={29} strokeWidth={1.4}/><h3>{String(t)}</h3><p>{String(d)}</p></article>})}</div><Link href='/strategic-plan-2027-2031' className='text-link'>Read the strategic framework <ArrowRight size={16}/></Link></section>}
